# Generated by Django 5.1 on 2024-08-21 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='instructor',
            name='descripcion',
            field=models.TextField(default='Descripción por defecto'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='instructor',
            name='num_estrellas',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='instructor',
            name='numero',
            field=models.CharField(default=900475834, max_length=9),
        ),
        migrations.CreateModel(
            name='InstructorEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.especialidad')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.instructor')),
            ],
        ),
    ]
