# Generated by Django 4.2.15 on 2024-08-21 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_especialidad_instructor_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='horario_disponible',
        ),
        migrations.AlterField(
            model_name='instructor',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='numero',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.instructor')),
            ],
        ),
    ]
