# Generated by Django 4.2.15 on 2024-08-26 17:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0005_cargo_estado_cargo_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorInfoPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redes_sociales', models.JSONField()),
                ('pasatiempos', models.TextField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=20)),
                ('telefono_emergencia', models.CharField(max_length=15)),
                ('nombre_contacto_emergencia', models.CharField(max_length=100)),
                ('relacion_contacto_emergencia', models.CharField(max_length=50)),
                ('email_personal', models.EmailField(max_length=100)),
                ('nivel_educacion', models.CharField(max_length=50)),
                ('idiomas', models.CharField(max_length=100)),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('disponibilidad_viaje', models.BooleanField(default=False)),
                ('preferencia_horario', models.CharField(max_length=50)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('instructor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mi_app.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_imagen', models.CharField(max_length=100)),
                ('fecha_obtencion', models.DateField()),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.instructor')),
            ],
        ),
    ]
